JEIEvents.information(e => {
//End Remastered
  e.addItem('endrem:black_eye', [Component.translate('info.endrem.black_eye')]),
  e.addItem('endrem:cold_eye', [Component.translate('info.endrem.cold_eye')]),
  e.addItem('endrem:corrupted_eye', [Component.translate('info.endrem.corrupted_eye')]),
  e.addItem('endrem:lost_eye', [Component.translate('info.endrem.lost_eye')]),
  e.addItem('endrem:nether_eye', [Component.translate('info.endrem.nether_eye')]),
  e.addItem('endrem:old_eye', [Component.translate('info.endrem.old_eye')]),
  e.addItem('endrem:rogue_eye', [Component.translate('info.endrem.rogue_eye')]),
  e.addItem('endrem:cursed_eye', [Component.translate('info.endrem.cursed_eye')]),
  e.addItem('endrem:evil_eye', [Component.translate('info.endrem.evil_eye')]),
  e.addItem('endrem:guardian_eye', [Component.translate('info.endrem.guardian_eye')]),
  e.addItem('endrem:magical_eye', [Component.translate('info.endrem.magical_eye')]),
  e.addItem('endrem:wither_eye', [Component.translate('info.endrem.wither_eye')]),
  e.addItem('endrem:witch_eye', [Component.translate('info.endrem.witch_eye')]),
  e.addItem('endrem:undead_eye', [Component.translate('info.endrem.undead_eye')]),
  e.addItem('endrem:exotic_eye', [Component.translate('info.endrem.exotic_eye')]),
  e.addItem('endrem:cryptic_eye', [Component.translate('info.endrem.cryptic_eye')]),

//Alexs Caves General
  e.addItem('alexscaves:cave_tablet', [Component.translate('info.alexscaves.cave_tablet')]),
  e.addItem('alexscaves:cave_codex', [Component.translate('info.alexscaves.cave_codex')]),

//Alexs Caves Magnetic Caves
  e.addItem('minecraft:iron_boots', [Component.translate('info.minecraft.iron_boots')]),
  e.addItem('alexscaves:scarlet_neodymium_node', [Component.translate('info.alexscaves.scarlet_neodymium_node')]),
  e.addItem('alexscaves:scarlet_neodymium_pillar', [Component.translate('info.alexscaves.scarlet_neodymium_pillar')]),
  e.addItem('alexscaves:block_of_scarlet_neodymium', [Component.translate('info.alexscaves.block_of_scarlet_neodymium')]),
  e.addItem('alexscaves:seeking_arrow', [Component.translate('info.alexscaves.seeking_arrow')]),
  e.addItem('alexscaves:magnetic_levitation_rail', [Component.translate('info.alexscaves.magnetic_levitation_rail')]),
  e.addItem('alexscaves:azure_magnet', [Component.translate('info.alexscaves.azure_magnet')]),
  e.addItem('alexscaves:scarlet_magnet', [Component.translate('info.alexscaves.scarlet_magnet')]),
  e.addItem('alexscaves:holocoder', [Component.translate('info.alexscaves.holocoder')]),
  e.addItem('alexscaves:quarry_smasher', [Component.translate('info.alexscaves.quarry_smasher')]),
  e.addItem('alexscaves:magnetic_light', [Component.translate('info.alexscaves.magnetic_light')]),
  e.addItem('alexscaves:quarry', [Component.translate('info.alexscaves.quarry')]),
  e.addItem('alexscaves:tesla_bulb', [Component.translate('info.alexscaves.tesla_bulb')]),
  e.addItem('alexscaves:galena_gauntlet', [Component.translate('info.alexscaves.galena_gauntlet')]),
  e.addItem('alexscaves:resistor_shield', [Component.translate('info.alexscaves.resistor_shield')]),
  e.addItem('alexscaves:heart_of_iron', [Component.translate('info.alexscaves.heart_of_iron')]),
  e.addItem('alexscaves:scrap_metal', [Component.translate('info.alexscaves.scrap_metal')]),
  e.addItem('alexscaves:scrap_metal_plate', [Component.translate('info.alexscaves.scrap_metal_plate')]),
  e.addItem('alexscaves:metal_rebar', [Component.translate('info.alexscaves.metal_rebar')]),
  e.addItem('alexscaves:metal_scaffolding', [Component.translate('info.alexscaves.metal_scaffolding')]),
  e.addItem('alexscaves:metal_barrel', [Component.translate('info.alexscaves.metal_barrel')]),

//Alexs Caves Primordial Cave
  e.addItem('alexscaves:limestone_spear', [Component.translate('info.alexscaves.limestone_spear')]),
  e.addItem('alexscaves:smooth_limestone', [Component.translate('info.alexscaves.smooth_limestone')]),
  e.addItem('minecraft:charcoal', [Component.translate('info.minecraft.charcoal')]),
  e.addItem('alexscaves:pine_nuts', [Component.translate('info.alexscaves.pine_nuts')]),
  e.addItem('alexscaves:tree_star', [Component.translate('info.alexscaves.tree_star')]),
  e.addItem('alexscaves:spawn_egg_subterranodon', [Component.translate('info.alexscaves.spawn_egg_subterranodon')]),
  e.addItem('alexscaves:spawn_egg_vallumraptor', [Component.translate('info.alexscaves.spawn_egg_vallumraptor')]),
  e.addItem('alexscaves:spawn_egg_grottoceratops', [Component.translate('info.alexscaves.spawn_egg_grottoceratops')]),
  e.addItem('alexscaves:spawn_egg_trilocaris', [Component.translate('info.alexscaves.spawn_egg_trilocaris')]),
  e.addItem('alexscaves:spawn_egg_tremorsaurus', [Component.translate('info.alexscaves.spawn_egg_tremorsaurus')]),
  e.addItem('alexscaves:spawn_egg_relicheirus', [Component.translate('info.alexscaves.spawn_egg_relicheirus')]),
  e.addItem('alexscaves:primordial_soup', [Component.translate('info.alexscaves.primordial_soup')]),
  e.addItem('alexscaves:amber_monolith', [Component.translate('info.alexscaves.amber_monolith')]),
  e.addItem('alexscaves:serene_salad', [Component.translate('info.alexscaves.serene_salad')]),
  e.addItem('alexscaves:seething_stew', [Component.translate('info.alexscaves.seething_stew')]),
  e.addItem('alexscaves:primitive_club', [Component.translate('info.alexscaves.primitive_club')]),
  e.addItem('alexscaves:primordial_helmet', [Component.translate('info.alexscaves.primordial_helmet')]),
  e.addItem('alexscaves:primordial_tunic', [Component.translate('info.alexscaves.primordial_tunic')]),
  e.addItem('alexscaves:primordial_pants', [Component.translate('info.alexscaves.primordial_pants')]),
  e.addItem('alexscaves:ominous_catalyst', [Component.translate('info.alexscaves.ominous_catalyst')]),
  e.addItem('alexscaves:tectonic_shard', [Component.translate('info.alexscaves.tectonic_shard')]),
  e.addItem('alexscaves:amber_curiosity', [Component.translate('info.alexscaves.amber_curiosity')]),
  e.addItem('alexscaves:ambersol', [Component.translate('info.alexscaves.ambersol')]),

//Alexs Caves Toxic Caves
  e.addItem('alexscaves:spawn_egg_nucleeper', [Component.translate('info.alexscaves.spawn_egg_nucleeper')]),  
  e.addItem('alexscaves:spawn_egg_radgill', [Component.translate('info.alexscaves.spawn_egg_radgill')]),  
  e.addItem('alexscaves:spawn_egg_gammaroach', [Component.translate('info.alexscaves.spawn_egg_gammaroach')]),  
  e.addItem('alexscaves:spawn_egg_raycat', [Component.translate('info.alexscaves.spawn_egg_raycat')]),  
  e.addItem('alexscaves:acid_bucket', [Component.translate('info.alexscaves.acid_bucket')]),
  e.addItem('alexscaves:unrefined_waste', [Component.translate('info.alexscaves.unrefined_waste')]),
  e.addItem('alexscaves:block_of_uranium', [Component.translate('info.alexscaves.block_of_uranium')]),
  e.addItem('alexscaves:uranium', [Component.translate('info.alexscaves.uranium')]),
  e.addItem('alexscaves:uranium_shard', [Component.translate('info.alexscaves.uranium_shard')]),
  e.addItem('alexscaves:uranium_rod', [Component.translate('info.alexscaves.uranium_rod')]),
  e.addItem('alexscaves:waste_drum', [Component.translate('info.alexscaves.waste_drum')]),
  e.addItem('alexscaves:charred_remnant', [Component.translate('info.alexscaves.charred_remnant')]),
  e.addItem('alexscaves:radrock_uranium_ore', [Component.translate('info.alexscaves.radrock_uranium_ore')]),
  e.addItem('alexscaves:sulfur', [Component.translate('info.alexscaves.sulfur')]),
  e.addItem('alexscaves:sulfur_bud_small', [Component.translate('info.alexscaves.sulfur_bud_small')]),
  e.addItem('alexscaves:sulfur_bud_medium', [Component.translate('info.alexscaves.sulfur_bud_medium')]),
  e.addItem('alexscaves:sulfur_bud_large', [Component.translate('info.alexscaves.sulfur_bud_large')]),
  e.addItem('alexscaves:sulfur_cluster', [Component.translate('info.alexscaves.sulfur_cluster')]),
  e.addItem('alexscaves:acidic_radrock', [Component.translate('info.alexscaves.acidic_radrock')]),
  e.addItem('spelunkery:sulfur', [Component.translate('info.spelunkery.sulfur')]),
  e.addItem('alexscaves:radon_bottle', [Component.translate('info.alexscaves.radon_bottle')]),
  e.addItem('alexscaves:disc_fragment_fusion', [Component.translate('info.alexscaves.disc_fragment_fusion')]),
  e.addItem('alexscaves:tremorzilla_egg', [Component.translate('info.alexscaves.tremorzilla_egg')]),
  e.addItem('alexscaves:spelunkie', [Component.translate('info.alexscaves.spelunkie')]),
  e.addItem('alexscaves:slam', [Component.translate('info.alexscaves.slam')]),
  e.addItem('alexscaves:green_soylent', [Component.translate('info.alexscaves.green_soylent')]),
  e.addItem('alexscaves:nuclear_bomb', [Component.translate('info.alexscaves.nuclear_bomb')]),
  e.addItem('alexscaves:nuclear_siren', [Component.translate('info.alexscaves.nuclear_siren')]),
  e.addItem('alexscaves:hazmat_mask', [Component.translate('info.alexscaves.hazmat_mask')]),
  e.addItem('alexscaves:hazmat_chestplate', [Component.translate('info.alexscaves.hazmat_chestplate')]),
  e.addItem('alexscaves:hazmat_leggings', [Component.translate('info.alexscaves.hazmat_leggings')]),
  e.addItem('alexscaves:hazmat_boots', [Component.translate('info.alexscaves.hazmat_boots')]),
  e.addItem('alexscaves:remote_detonator', [Component.translate('info.alexscaves.remote_detonator')]),
  e.addItem('alexscaves:raygun', [Component.translate('info.alexscaves.raygun')]),
  e.addItem('alexscaves:nuclear_furnace_component', [Component.translate('info.alexscaves.nuclear_furnace_component')]),

//Alexs Caves Abyssal Caves
  e.addItem('alexscaves:spawn_egg_sea_pig', [Component.translate('info.alexscaves.spawn_egg_sea_pig')]), 
  e.addItem('alexscaves:spawn_egg_hullbreaker', [Component.translate('info.alexscaves.spawn_egg_hullbreaker')]), 
  e.addItem('alexscaves:spawn_egg_gossamer_worm', [Component.translate('info.alexscaves.spawn_egg_gossamer_worm')]), 
  e.addItem('alexscaves:spawn_egg_tripodfish', [Component.translate('info.alexscaves.spawn_egg_tripodfish')]), 
  e.addItem('alexscaves:spawn_egg_lanternfish', [Component.translate('info.alexscaves.spawn_egg_lanternfish')]), 
  e.addItem('alexscaves:spawn_egg_deep_one', [Component.translate('info.alexscaves.spawn_egg_deep_one')]), 
  e.addItem('alexscaves:spawn_egg_deep_one_knight', [Component.translate('info.alexscaves.spawn_egg_deep_one_knight')]), 
  e.addItem('alexscaves:spawn_egg_deep_one_mage', [Component.translate('info.alexscaves.spawn_egg_deep_one_mage')]), 
  e.addItem('alexscaves:mussel', [Component.translate('info.alexscaves.mussel')]),   
  e.addItem('alexscaves:pearl', [Component.translate('info.alexscaves.pearl')]), 
  e.addItem('alexscaves:depth_glass', [Component.translate('info.alexscaves.depth_glass')]),   
  e.addItem('alexscaves:gazing_pearl', [Component.translate('info.alexscaves.gazing_pearl')]),  
  e.addItem('alexscaves:sea_glass_shards', [Component.translate('info.alexscaves.sea_glass_shards')]),   
  e.addItem('alexscaves:marine_snow', [Component.translate('info.alexscaves.marine_snow')]),   
  e.addItem('alexscaves:ortholance', [Component.translate('info.alexscaves.ortholance')]),   
  e.addItem('alexscaves:magic_conch', [Component.translate('info.alexscaves.magic_conch')]),   
  e.addItem('alexscaves:sea_staff', [Component.translate('info.alexscaves.sea_staff')]),   
  e.addItem('alexscaves:depth_charge', [Component.translate('info.alexscaves.depth_charge')]),   
  e.addItem('alexscaves:floater', [Component.translate('info.alexscaves.floater')]),   
  e.addItem('alexscaves:bioluminescent_torch', [Component.translate('info.alexscaves.bioluminescent_torch')]),   
  e.addItem('alexscaves:diving_helmet', [Component.translate('info.alexscaves.diving_helmet')]), 
  e.addItem('alexscaves:diving_leggings', [Component.translate('info.alexscaves.diving_leggings')]),   
  e.addItem('alexscaves:diving_boots', [Component.translate('info.alexscaves.diving_boots')]),   
  e.addItem('alexscaves:drain', [Component.translate('info.alexscaves.drain')]),   
  e.addItem('alexscaves:submarine', [Component.translate('info.alexscaves.submarine')]),   
  e.addItem('alexscaves:enigmatic_engine', [Component.translate('info.alexscaves.enigmatic_engine')]),   

//Alexs Caves Candy Cavity
  e.addItem('alexscaves:spawn_egg_sweetish_fish', [Component.translate('info.alexscaves.spawn_egg_sweetish_fish')]),
  e.addItem('alexscaves:spawn_egg_candicorn', [Component.translate('info.alexscaves.spawn_egg_candicorn')]),
  e.addItem('alexscaves:spawn_egg_gum_worm', [Component.translate('info.alexscaves.spawn_egg_gum_worm')]),
  e.addItem('alexscaves:gobthumper', [Component.translate('info.alexscaves.gobthumper')]),
  e.addItem('alexscaves:candy_cane_hook', [Component.translate('info.alexscaves.candy_cane_hook')]),
  e.addItem('alexscaves:spawn_egg_gummy_bear', [Component.translate('info.alexscaves.spawn_egg_gummy_bear')]),
  e.addItem('alexscaves:jelly_bean', [Component.translate('info.alexscaves.jelly_bean')]),
  e.addItem('alexscaves:licoroot', [Component.translate('info.alexscaves.licoroot')]),
  e.addItem('alexscaves:spawn_egg_gingerbread_man', [Component.translate('info.alexscaves.spawn_egg_gingerbread_man')]),
  e.addItem('alexscaves:gingerbarrel', [Component.translate('info.alexscaves.gingerbarrel')]),
  e.addItem('alexscaves:gingerbread_helmet', [Component.translate('info.alexscaves.gingerbread_helmet')]),
  e.addItem('alexscaves:gingerbread_chestplate', [Component.translate('info.alexscaves.gingerbread_chestplate')]),
  e.addItem('alexscaves:gingerbread_leggings', [Component.translate('info.alexscaves.gingerbread_leggings')]),
  e.addItem('alexscaves:gingerbread_boots', [Component.translate('info.alexscaves.gingerbread_boots')]),
  e.addItem('alexscaves:sundrop', [Component.translate('info.alexscaves.sundrop')]),
  e.addItem('alexscaves:vanilla_ice_cream_scoop', [Component.translate('info.alexscaves.vanilla_ice_cream_scoop')]),
  e.addItem('alexscaves:chocolate_ice_cream_scoop', [Component.translate('info.alexscaves.chocolate_ice_cream_scoop')]),
  e.addItem('alexscaves:sweetberry_ice_cream_scoop', [Component.translate('info.alexscaves.sweetberry_ice_cream_scoop')]),
  e.addItem('alexscaves:hot_chocolate_bottle', [Component.translate('info.alexscaves.hot_chocolate_bottle')]),
  e.addItem('alexscaves:sugar_staff', [Component.translate('info.alexscaves.sugar_staff')]),
  e.addItem('alexscaves:frostmint', [Component.translate('info.alexscaves.frostmint')]),
  e.addItem('alexscaves:purple_soda_bottle', [Component.translate('info.alexscaves.purple_soda_bottle')]),
  e.addItem('alexscaves:purple_soda_bucket', [Component.translate('info.alexscaves.purple_soda_bucket')]),
  e.addItem('alexscaves:rainbounce_boots', [Component.translate('info.alexscaves.rainbounce_boots')]),
  e.addItem('alexscaves:gumball_pile', [Component.translate('info.alexscaves.gumball_pile')]),
  e.addItem('alexscaves:shot_gum', [Component.translate('info.alexscaves.shot_gum')]),
  e.addItem('alexscaves:confection_oven', [Component.translate('info.alexscaves.confection_oven')]),
  e.addItem('alexscaves:sack_of_sating', [Component.translate('info.alexscaves.sack_of_sating')]),
  e.addItem('alexscaves:conversion_crucible', [Component.translate('info.alexscaves.conversion_crucible')]),
  e.addItem('alexscaves:biome_treat', [Component.translate('info.alexscaves.biome_treat')]),

//Alexs Caves Forlorn Hollow
  e.addItem('alexscaves:spawn_egg_gloomoth', [Component.translate('info.alexscaves.spawn_egg_gloomoth')]), 
  e.addItem('alexscaves:spawn_egg_underzealot', [Component.translate('info.alexscaves.spawn_egg_underzealot')]), 
  e.addItem('alexscaves:spawn_egg_watcher', [Component.translate('info.alexscaves.spawn_egg_watcher')]), 
  e.addItem('alexscaves:spawn_egg_corrodent', [Component.translate('info.alexscaves.spawn_egg_corrodent')]), 
  e.addItem('alexscaves:spawn_egg_vesper', [Component.translate('info.alexscaves.spawn_egg_vesper')]), 
  e.addItem('alexscaves:spawn_egg_forsaken', [Component.translate('info.alexscaves.spawn_egg_forsaken')]), 
  e.addItem('alexscaves:fertilizer', [Component.translate('info.alexscaves.fertilizer')]), 
  e.addItem('alexscaves:moth_dust', [Component.translate('info.alexscaves.moth_dust')]), 
  e.addItem('alexscaves:moth_ball', [Component.translate('info.alexscaves.moth_ball')]), 
  e.addItem('alexscaves:desolate_dagger', [Component.translate('info.alexscaves.desolate_dagger')]), 
  e.addItem('alexscaves:totem_of_possession', [Component.translate('info.alexscaves.totem_of_possession')]), 
  e.addItem('alexscaves:beholder', [Component.translate('info.alexscaves.beholder')]), 
  e.addItem('alexscaves:burrowing_arrow', [Component.translate('info.alexscaves.burrowing_arrow')]), 
  e.addItem('alexscaves:dreadbow', [Component.translate('info.alexscaves.dreadbow')]), 
  e.addItem('alexscaves:hood_of_darkness', [Component.translate('info.alexscaves.hood_of_darkness')]), 
  e.addItem('alexscaves:cloak_of_darkness', [Component.translate('info.alexscaves.cloak_of_darkness')]), 
  e.addItem('alexscaves:darkened_apple', [Component.translate('info.alexscaves.darkened_apple')]), 
  e.addItem('alexscaves:guano', [Component.translate('info.alexscaves.guano')]), 

//Alexs Mobs Mob JEI Info
  e.addItem('alexsmobs:spawn_egg_grizzly_bear', [Component.translate('info.alexsmobs.spawn_egg_grizzly_bear')]),
  e.addItem('alexsmobs:spawn_egg_crocodile', ['Hostile, but can be bred with rotten flesh.', 'Crocodiles growing up around a player will defend its area of birth from monsters.']),
  e.addItem('alexsmobs:spawn_egg_fly', [Component.translate('info.alexsmobs.spawn_egg_fly')]),
  e.addItem('alexsmobs:spawn_egg_hummingbird', [Component.translate('info.alexsmobs.spawn_egg_hummingbird')]),
  e.addItem('alexsmobs:spawn_egg_orca', [Component.translate('info.alexsmobs.spawn_egg_orca')]),
  e.addItem('alexsmobs:spawn_egg_sunbird', ['Orbits any beacon it can find and sets nearby undead mobs on fire.', 'Grants Sunbirds Blessing when flying nearby and Sunbirds Curse if attacked.']),
  e.addItem('alexsmobs:spawn_egg_gorilla', [Component.translate('info.alexsmobs.spawn_egg_gorilla')]),
  e.addItem('alexsmobs:spawn_egg_endergrade', [Component.translate('info.alexsmobs.spawn_egg_endergrade')]),
  e.addItem('alexsmobs:spawn_egg_hammerhead_shark', [Component.translate('info.alexsmobs.spawn_egg_hammerhead_shark')]),
  e.addItem('alexsmobs:spawn_egg_komodo_dragon', ['Tamed with stacks of Rotten Flesh and can be saddled.', 'Occasionally drops Komodo Dragon Spit.']),  
  e.addItem('alexsmobs:spawn_egg_capuchin_monkey', ['Tamed with Bananas, obtained by breaking Jungle Leaves.', 'Can ride the owners shoulder. Feed Eggs to heal, bred with Maggots, give Cobblestone or Ancient Darts to let them use their ranged attack.']),
  e.addItem('alexsmobs:spawn_egg_warped_toad', [Component.translate('info.alexsmobs.spawn_egg_warped_toad')]),
  e.addItem('alexsmobs:spawn_egg_moose', [Component.translate('info.alexsmobs.spawn_egg_moose')]),
  e.addItem('alexsmobs:spawn_egg_raccoon', ['Steals food out of chests.', 'Tamed if given a Chicken Egg near water to wash and bred with Bread. Give a Carpet to give them a bandana and remove with shears.', 'Rarely steals items from Villager inventories.']),
  e.addItem('alexsmobs:spawn_egg_blobfish', [Component.translate('info.alexsmobs.spawn_egg_blobfish')]),
  e.addItem('alexsmobs:spawn_egg_seal', [Component.translate('info.alexsmobs.spawn_egg_seal')]),
  e.addItem('alexsmobs:spawn_egg_cockroach', [Component.translate('info.alexsmobs.spawn_egg_cockroach')]),
  e.addItem('alexsmobs:spawn_egg_shoebill', [Component.translate('info.alexsmobs.spawn_egg_shoebill')]),
  e.addItem('alexsmobs:spawn_egg_elephant', ['Tame calfs and non-tusked Elephants with Acacia Blossoms and breed tamed Elephants with Acacia Blossoms.', 'Can be ridden, given Chests, and given Carpets. Remove with Shears.', 'Tamed Tusked Elephants can be made to charge by feeding Wheat.']),
  e.addItem('alexsmobs:spawn_egg_snow_leopard', [Component.translate('info.alexsmobs.spawn_egg_snow_leopard')]),
  e.addItem('alexsmobs:spawn_egg_spectre', [Component.translate('info.alexsmobs.spawn_egg_spectre')]),
  e.addItem('alexsmobs:spawn_egg_crow', [Component.translate('info.alexsmobs.spawn_egg_crow')]),
  e.addItem('alexsmobs:spawn_egg_alligator_snapping_turtle', [Component.translate('info.alexsmobs.spawn_egg_alligator_snapping_turtle')]),
  e.addItem('alexsmobs:spawn_egg_mungus', [Component.translate('info.alexsmobs.spawn_egg_mungus')]),
  e.addItem('alexsmobs:spawn_egg_mantis_shrimp', [Component.translate('info.alexsmobs.spawn_egg_mantis_shrimp')]),
  e.addItem('alexsmobs:spawn_egg_warped_mosco', [Component.translate('info.alexsmobs.spawn_egg_warped_mosco')]),
  e.addItem('alexsmobs:spawn_egg_straddler', [Component.translate('info.alexsmobs.spawn_egg_straddler')]),
  e.addItem('alexsmobs:spawn_egg_stradpole', [Component.translate('info.alexsmobs.spawn_egg_stradpole')]),
  e.addItem('alexsmobs:spawn_egg_emu', [Component.translate('info.alexsmobs.spawn_egg_emu')]),
  e.addItem('alexsmobs:spawn_egg_platypus', [Component.translate('info.alexsmobs.spawn_egg_platypus')]),  
  e.addItem('alexsmobs:spawn_egg_tasmanian_devil', [Component.translate('info.alexsmobs.spawn_egg_tasmanian_devil')]),
  e.addItem('alexsmobs:spawn_egg_kangaroo', [Component.translate('info.alexsmobs.spawn_egg_kangaroo')]),
  e.addItem('alexsmobs:spawn_egg_cachalot_whale', [Component.translate('info.alexsmobs.spawn_egg_cachalot_whale')]),
  e.addItem('alexsmobs:spawn_egg_leafcutter_ant', [Component.translate('info.alexsmobs.spawn_egg_leafcutter_ant')]),
  e.addItem('alexsmobs:spawn_egg_enderiophage', [Component.translate('info.alexsmobs.spawn_egg_enderiophage')]),
  e.addItem('alexsmobs:spawn_egg_bald_eagle', [Component.translate('info.alexsmobs.spawn_egg_bald_eagle')]),
  e.addItem('alexsmobs:spawn_egg_tiger', [Component.translate('info.alexsmobs.spawn_egg_tiger')]),
  e.addItem('alexsmobs:spawn_egg_tarantula_hawk', [Component.translate('info.alexsmobs.spawn_egg_tarantula_hawk')]),
  e.addItem('alexsmobs:spawn_egg_void_worm', [Component.translate('info.alexsmobs.spawn_egg_void_worm')]),
  e.addItem('alexsmobs:spawn_egg_frilled_shark', [Component.translate('info.alexsmobs.spawn_egg_frilled_shark')]),
  e.addItem('alexsmobs:spawn_egg_mimic_octopus', [Component.translate('info.alexsmobs.spawn_egg_mimic_octopus')]),
  e.addItem('alexsmobs:spawn_egg_seagull', [Component.translate('info.alexsmobs.spawn_egg_seagull')]),
  e.addItem('alexsmobs:spawn_egg_froststalker', [Component.translate('info.alexsmobs.spawn_egg_froststalker')]),
  e.addItem('alexsmobs:spawn_egg_tusklin', [Component.translate('info.alexsmobs.spawn_egg_tusklin')]),
  e.addItem('alexsmobs:spawn_egg_laviathan', [Component.translate('info.alexsmobs.spawn_egg_laviathan')]),
  e.addItem('alexsmobs:spawn_egg_cosmaw', [Component.translate('info.alexsmobs.spawn_egg_cosmaw')]),
  e.addItem('alexsmobs:spawn_egg_toucan', [Component.translate('info.alexsmobs.spawn_egg_toucan')]),
  e.addItem('alexsmobs:spawn_egg_maned_wolf', [Component.translate('info.alexsmobs.spawn_egg_maned_wolf')]),
  e.addItem('alexsmobs:spawn_egg_anaconda', [Component.translate('info.alexsmobs.spawn_egg_anaconda')]),
  e.addItem('alexsmobs:spawn_egg_anteater', [Component.translate('info.alexsmobs.spawn_egg_anteater')]),
  e.addItem('alexsmobs:spawn_egg_flutter', [Component.translate('info.alexsmobs.spawn_egg_flutter')]),
  e.addItem('alexsmobs:spawn_egg_gelada_monkey', [Component.translate('info.alexsmobs.spawn_egg_gelada_monkey')]),
  e.addItem('alexsmobs:spawn_egg_jerboa', [Component.translate('info.alexsmobs.spawn_egg_jerboa')]),
  e.addItem('alexsmobs:spawn_egg_terrapin', [Component.translate('info.alexsmobs.spawn_egg_terrapin')]),
  e.addItem('alexsmobs:spawn_egg_comb_jelly', [Component.translate('info.alexsmobs.spawn_egg_comb_jelly')]),
  e.addItem('alexsmobs:spawn_egg_cosmic_cod', [Component.translate('info.alexsmobs.spawn_egg_cosmic_cod')]),
  e.addItem('alexsmobs:spawn_egg_bunfungus', [Component.translate('info.alexsmobs.spawn_egg_bunfungus')]),
  e.addItem('alexsmobs:spawn_egg_bison', [Component.translate('info.alexsmobs.spawn_egg_bison')]),
  e.addItem('alexsmobs:spawn_egg_giant_squid', [Component.translate('info.alexsmobs.spawn_egg_giant_squid')]),
  e.addItem('alexsmobs:spawn_egg_devils_hole_pupfish', [Component.translate('info.alexsmobs.spawn_egg_devils_hole_pupfish')]),
  e.addItem('alexsmobs:spawn_egg_catfish', [Component.translate('info.alexsmobs.spawn_egg_catfish')]),
  e.addItem('alexsmobs:small_catfish_bucket', [Component.translate('info.alexsmobs.small_catfish_bucket')]),
  e.addItem('alexsmobs:medium_catfish_bucket', [Component.translate('info.alexsmobs.medium_catfish_bucket')]),
  e.addItem('alexsmobs:large_catfish_bucket', [Component.translate('info.alexsmobs.large_catfish_bucket')]),
  e.addItem('alexsmobs:spawn_egg_flying_fish', [Component.translate('info.alexsmobs.spawn_egg_flying_fish')]),
  e.addItem('alexsmobs:spawn_egg_rain_frog', [Component.translate('info.alexsmobs.spawn_egg_rain_frog')]),
  e.addItem('alexsmobs:spawn_egg_potoo', [Component.translate('info.alexsmobs.spawn_egg_potoo')]),
  e.addItem('alexsmobs:spawn_egg_mudskipper', [Component.translate('info.alexsmobs.spawn_egg_mudskipper')]),
  e.addItem('alexsmobs:spawn_egg_rhinoceros', [Component.translate('info.alexsmobs.spawn_egg_rhinoceros')]),
  e.addItem('alexsmobs:spawn_egg_sugar_glider', [Component.translate('info.alexsmobs.spawn_egg_sugar_glider')]),
  e.addItem('alexsmobs:spawn_egg_farseer', [Component.translate('info.alexsmobs.spawn_egg_farseer')]),
  e.addItem('alexsmobs:spawn_egg_skreecher', [Component.translate('info.alexsmobs.spawn_egg_skreecher')]),
  e.addItem('alexsmobs:spawn_egg_underminer', [Component.translate('info.alexsmobs.spawn_egg_underminer')]),
  e.addItem('alexsmobs:spawn_egg_skunk', [Component.translate('info.alexsmobs.spawn_egg_skunk')]),
  e.addItem('alexsmobs:spawn_egg_banana_slug', [Component.translate('info.alexsmobs.spawn_egg_banana_slug')]),
  e.addItem('alexsmobs:spawn_egg_blue_jay', [Component.translate('info.alexsmobs.spawn_egg_blue_jay')]),
  e.addItem('alexsmobs:spawn_egg_caiman', [Component.translate('info.alexsmobs.spawn_egg_caiman')]),
  e.addItem('alexsmobs:spawn_egg_triops', [Component.translate('info.alexsmobs.spawn_egg_triops')]),

  //Alexs Mobs Item JEI Info
  e.addItem('alexsmobs:banana_peel', [Component.translate('info.alexsmobs.banana_peel')]),
  e.addItem('alexsmobs:banana', [Component.translate('info.alexsmobs.banana')]),
  e.addItem('alexsmobs:fedora', [Component.translate('info.alexsmobs.fedora')]),
  e.addItem('alexsmobs:cachalot_whale_tooth', [Component.translate('info.alexsmobs.cachalot_whale_tooth')]),
  e.addItem('alexsmobs:shrimp_fried_rice', [Component.translate('info.alexsmobs.shrimp_fried_rice')]),
  e.addItem('alexsmobs:sombrero', [Component.translate('info.alexsmobs.sombrero')]),
  e.addItem('alexsmobs:crocodile_scute', [Component.translate('info.alexsmobs.crocodile_scute')]),
  e.addItem('alexsmobs:blood_sac', [Component.translate('info.alexsmobs.blood_sac')]),
  e.addItem('alexsmobs:blood_sprayer', [Component.translate('info.alexsmobs.blood_sprayer')]),
  e.addItem('alexsmobs:ancient_dart', [Component.translate('info.alexsmobs.ancient_dart')]),
  e.addItem('alexsmobs:chorus_on_a_stick', [Component.translate('info.alexsmobs.chorus_on_a_stick')]),
  e.addItem('alexsmobs:mosquito_larva', [Component.translate('info.alexsmobs.mosquito_larva')]),
  e.addItem('alexsmobs:shark_tooth', [Component.translate('info.alexsmobs.shark_tooth')]),  
  e.addItem('alexsmobs:shark_tooth_arrow', [Component.translate('info.alexsmobs.shark_tooth_arrow')]),  
  e.addItem('alexsmobs:komodo_spit', [Component.translate('info.alexsmobs.komodo_spit')]),
  e.addItem('alexsmobs:moose_antler', [Component.translate('info.alexsmobs.moose_antler')]),
  e.addItem('alexsmobs:mimicream', [Component.translate('info.alexsmobs.mimicream')]),
  e.addItem('alexsmobs:fish_oil', [Component.translate('info.alexsmobs.fish_oil')]),
  e.addItem('alexsmobs:maraca', [Component.translate('info.alexsmobs.maraca')]),
  e.addItem('alexsmobs:sombrero', [Component.translate('info.alexsmobs.sombrero')]),
  e.addItem('alexsmobs:cockroach_ootheca', [Component.translate('info.alexsmobs.cockroach_ootheca')]),
  e.addItem('alexsmobs:acacia_blossom', [Component.translate('info.alexsmobs.acacia_blossom')]),
  e.addItem('alexsmobs:spiked_scute', [Component.translate('info.alexsmobs.spiked_scute')]),
  e.addItem('alexsmobs:pocket_sand', [Component.translate('info.alexsmobs.pocket_sand')]),
  e.addItem('alexsmobs:gustmaker', [Component.translate('info.alexsmobs.gustmaker')]),
  e.addItem('alexsmobs:straddleboard', [Component.translate('info.alexsmobs.straddleboard')]),
  e.addItem('alexsmobs:ambergris', [Component.translate('info.alexsmobs.ambergris')]),
  e.addItem('alexsmobs:echolocator', [Component.translate('info.alexsmobs.echolocator')]),
  e.addItem('alexsmobs:endolocator', [Component.translate('info.alexsmobs.endolocator')]),
  e.addItem('alexsmobs:straddle_saddle', [Component.translate('info.alexsmobs.straddle_saddle')]),
  e.addItem('alexsmobs:straddle_helmet', [Component.translate('info.alexsmobs.straddle_helmet')]),
  e.addItem('alexsmobs:mungal_spores', [Component.translate('info.alexsmobs.mungal_spores')]),
  e.addItem('alexsmobs:squid_grapple', [Component.translate('info.alexsmobs.squid_grapple')]),
  e.addItem('alexsmobs:lost_tentacle', [Component.translate('info.alexsmobs.lost_tentacle')]),
  e.addItem('alexsmobs:pupfish_locator', [Component.translate('info.alexsmobs.pupfish_locator')]),
  e.addItem('alexsmobs:novelty_hat', [Component.translate('info.alexsmobs.novelty_hat')]),
  e.addItem('alexsmobs:leafcutter_ant_pupa', [Component.translate('info.alexsmobs.leafcutter_ant_pupa')]),
  e.addItem('alexsmobs:gongylidia', [Component.translate('info.alexsmobs.gongylidia')]),
  e.addItem('alexsmobs:enderiophage_rocket', [Component.translate('info.alexsmobs.enderiophage_rocket')]),
  e.addItem('alexsmobs:capsid', [Component.translate('info.alexsmobs.capsid')]),
  e.addItem('alexsmobs:falconry_glove', [Component.translate('info.alexsmobs.falconry_glove')]),
  e.addItem('alexsmobs:falconry_hood', ['Used to control Bald Eagles while they are flying.'])
  e.addItem('alexsmobs:mysterious_worm', [Component.translate('info.alexsmobs.mysterious_worm')]),
  e.addItem('alexsmobs:dimensional_carver', [Component.translate('info.alexsmobs.dimensional_carver')]),
  e.addItem('alexsmobs:shattered_dimensional_carver', [Component.translate('info.alexsmobs.shattered_dimensional_carver')]),
  e.addItem('alexsmobs:serrated_shark_tooth', [Component.translate('info.alexsmobs.serrated_shark_tooth')]),
  e.addItem('alexsmobs:shield_of_the_deep', [Component.translate('info.alexsmobs.shield_of_the_deep')]),
  e.addItem('alexsmobs:pigshoes', [Component.translate('info.alexsmobs.pigshoes')]),
  e.addItem('alexsmobs:shed_snake_skin', [Component.translate('info.alexsmobs.shed_snake_skin')]),
  e.addItem('alexsmobs:vine_lasso', [Component.translate('info.alexsmobs.vine_lasso')]),
  e.addItem('alexsmobs:rainbow_jelly', [Component.translate('info.alexsmobs.rainbow_jelly')]),
  e.addItem('alexsmobs:sculk_boomer', [Component.translate('info.alexsmobs.sculk_boomer')]),
  e.addItem('alexsmobs:transmutation_table', [Component.translate('info.alexsmobs.transmutation_table')]),
  e.addItem('alexsmobs:ghostly_pickaxe', [Component.translate('info.alexsmobs.ghostly_pickaxe')]),
  e.addItem('alexsmobs:tendon_whip', [Component.translate('info.alexsmobs.tendon_whip')]),
  e.addItem('alexsmobs:unsettling_kimono', [Component.translate('info.alexsmobs.unsettling_kimono')]),
  e.addItem('alexsmobs:stink_bottle', [Component.translate('info.alexsmobs.stink_bottle')]),
  e.addItem('alexsmobs:stink_ray', [Component.translate('info.alexsmobs.stink_ray')]),
  e.addItem('alexsmobs:banana_slug_slime_block', [Component.translate('info.alexsmobs.banana_slug_slime_block')]),
  e.addItem('alexsmobs:mosquito_repellent_stew', [Component.translate('info.alexsmobs.mosquito_repellent_stew')]),
  e.addItem('alexsmobs:music_disc_thime', [Component.translate('info.alexsmobs.music_disc_thime')]),
  e.addItem('alexsmobs:hummingbird_feeder', [Component.translate('info.alexsmobs.hummingbird_feeder')]),
  e.addItem('alexsmobs:caiman_egg', [Component.translate('info.alexsmobs.caiman_egg')]),
  e.addItem('alexsmobs:crocodile_egg', [Component.translate('info.alexsmobs.crocodile_egg')]),
  e.addItem('alexsmobs:triops_eggs', [Component.translate('info.alexsmobs.triops_eggs')]),

//Berry Good
  e.addItem('berry_good:music_disc_fox', [Component.translate('info.berry_good.music_disc_fox')]),
  e.addItem('minecraft:sweet_berries', [Component.translate('info.minecraft.sweet_berries')]),
  e.addItem('minecraft:glow_berries', [Component.translate('info.minecraft.glow_berries')]),

//Biome Makeover
  e.addItem('biomemakeover:poltergeist', [Component.translate('info.biomemakeover.poltergeist')]),
  e.addItem('biomemakeover:peat', [Component.translate('info.biomemakeover.peat')]),
  e.addItem('biomemakeover:peat_farmland', [Component.translate('info.biomemakeover.peat_farmland')]),
  e.addItem('biomemakeover:dried_peat', [Component.translate('info.biomemakeover.dried_peat')]),
  e.addItem('biomemakeover:lightning_bug_bottle', [Component.translate('info.biomemakeover.lightning_bug_bottle')]),
  e.addItem('biomemakeover:altar', [Component.translate('info.biomemakeover.altar')]),
  e.addItem('biomemakeover:cladded_stone', [Component.translate('info.biomemakeover.cladded_stone')]),
  e.addItem('biomemakeover:lightning_bottle', [Component.translate('info.biomemakeover.lightning_bottle')]),
  e.addItem('biomemakeover:soul_embers', [Component.translate('info.biomemakeover.soul_embers')]),
  e.addItem('biomemakeover:stunt_powder', [Component.translate('info.biomemakeover.stunt_powder')]),
  e.addItem('biomemakeover:enchanted_totem', [Component.translate('info.biomemakeover.enchanted_totem')]),
  e.addItem('biomemakeover:cladded_boots', [Component.translate('info.biomemakeover.cladded_boots')]),

//Domestication Innovation
  e.addItem('domesticationinnovation:pet_bed_white', [Component.translate('info.domesticationinnovation.pet_bed_white')]),
  e.addItem('domesticationinnovation:pet_bed_orange', [Component.translate('info.domesticationinnovation.pet_bed_orange')]),
  e.addItem('domesticationinnovation:pet_bed_magenta', [Component.translate('info.domesticationinnovation.pet_bed_magenta')]),
  e.addItem('domesticationinnovation:pet_bed_light_blue', [Component.translate('info.domesticationinnovation.pet_bed_light_blue')]),
  e.addItem('domesticationinnovation:pet_bed_yellow', [Component.translate('info.domesticationinnovation.pet_bed_yellow')]),
  e.addItem('domesticationinnovation:pet_bed_lime', [Component.translate('info.domesticationinnovation.pet_bed_lime')]),
  e.addItem('domesticationinnovation:pet_bed_pink', [Component.translate('info.domesticationinnovation.pet_bed_pink')]),
  e.addItem('domesticationinnovation:pet_bed_gray', [Component.translate('info.domesticationinnovation.pet_bed_gray')]),
  e.addItem('domesticationinnovation:pet_bed_light_gray', [Component.translate('info.domesticationinnovation.pet_bed_light_gray')]),
  e.addItem('domesticationinnovation:pet_bed_cyan', [Component.translate('info.domesticationinnovation.pet_bed_cyan')]),
  e.addItem('domesticationinnovation:pet_bed_purple', [Component.translate('info.domesticationinnovation.pet_bed_purple')]),
  e.addItem('domesticationinnovation:pet_bed_blue', [Component.translate('info.domesticationinnovation.pet_bed_blue')]),
  e.addItem('domesticationinnovation:pet_bed_brown', [Component.translate('info.domesticationinnovation.pet_bed_brown')]),
  e.addItem('domesticationinnovation:pet_bed_green', [Component.translate('info.domesticationinnovation.pet_bed_green')]),
  e.addItem('domesticationinnovation:pet_bed_red', [Component.translate('info.domesticationinnovation.pet_bed_red')]),
  e.addItem('domesticationinnovation:pet_bed_black', [Component.translate('info.domesticationinnovation.pet_bed_black')]),
  e.addItem('domesticationinnovation:collar_tag', [Component.translate('info.domesticationinnovation.collar_tag')]),
  e.addItem('domesticationinnovation:feather_on_a_stick', [Component.translate('info.domesticationinnovation.feather_on_a_stick')]),
  e.addItem('domesticationinnovation:rotten_apple', [Component.translate('info.domesticationinnovation.rotten_apple')]),
  e.addItem('domesticationinnovation:sinister_carrot', [Component.translate('info.domesticationinnovation.sinister_carrot')]),
  e.addItem('domesticationinnovation:deed_of_ownership', [Component.translate('info.domesticationinnovation.deed_of_ownership')]),
  e.addItem('domesticationinnovation:drum', [Component.translate('info.domesticationinnovation.drum')]),
  e.addItem('domesticationinnovation:wayward_lantern', [Component.translate('info.domesticationinnovation.wayward_lantern')]),

//Dragonseeker
  e.addItem('dragonseeker:dragonseeker', [Component.translate('info.dragonseeker.dragonseeker')]),
  e.addItem('dragonseeker:epic_dragonseeker', [Component.translate('info.dragonseeker.epic_dragonseeker')]),
  e.addItem('dragonseeker:legendary_dragonseeker', [Component.translate('info.dragonseeker.legendary_dragonseeker')]),

//Forbidden and Arcanus
  e.addItem('forbidden_arcanus:growing_edelwood', [Component.translate('info.forbidden_arcanus.growing_edelwood')]),
  e.addItem('forbidden_arcanus:spectral_eye_amulet', [Component.translate('info.forbidden_arcanus.spectral_eye_amulet')]),
  e.addItem('forbidden_arcanus:magical_farmland', [Component.translate('info.forbidden_arcanus.magical_farmland')]),
  e.addItem('forbidden_arcanus:quantum_catcher', [Component.translate('info.forbidden_arcanus.quantum_catcher')]),
  e.addItem('forbidden_arcanus:arcane_bone_meal', [Component.translate('info.forbidden_arcanus.arcane_bone_meal')]),
  e.addItem('forbidden_arcanus:yellow_orchid', [Component.translate('info.forbidden_arcanus.yellow_orchid')]),
  e.addItem('forbidden_arcanus:darkstone', [Component.translate('info.forbidden_arcanus.darkstone')]),
  e.addItem('forbidden_arcanus:edelwood_bucket', [Component.translate('info.forbidden_arcanus.edelwood_bucket')]),
  e.addItem('forbidden_arcanus:dark_matter', [Component.translate('info.forbidden_arcanus.dark_matter')]),
  e.addItem('forbidden_arcanus:edelwood_log', [Component.translate('info.forbidden_arcanus.edelwood_log')]),
  e.addItem('forbidden_arcanus:stellarite_piece', [Component.translate('info.forbidden_arcanus.stellarite_piece')]),
  e.addItem('forbidden_arcanus:blood_test_tube', [Component.translate('info.forbidden_arcanus.blood_test_tube')]),
  e.addItem('forbidden_arcanus:magnetized_darkstone_pedestal', [Component.translate('info.forbidden_arcanus.magnetized_darkstone_pedestal')]),
  e.addItem('forbidden_arcanus:draco_arcanus_scepter', [Component.translate('info.forbidden_arcanus.draco_arcanus_scepter')]),
  e.addItem('forbidden_arcanus:mystical_dagger', [Component.translate('info.forbidden_arcanus.mystical_dagger')]),
  e.addItem('forbidden_arcanus:ferrognetic_mixture', [Component.translate('info.forbidden_arcanus.ferrognetic_mixture')]),
  e.addItem('forbidden_arcanus:wooden_blacksmith_gavel', [Component.translate('info.forbidden_arcanus.wooden_blacksmith_gavel')]),
  e.addItem('forbidden_arcanus:stone_blacksmith_gavel', [Component.translate('info.forbidden_arcanus.stone_blacksmith_gavel')]),
  e.addItem('forbidden_arcanus:golden_blacksmith_gavel', [Component.translate('info.forbidden_arcanus.golden_blacksmith_gavel')]),
  e.addItem('forbidden_arcanus:iron_blacksmith_gavel', [Component.translate('info.forbidden_arcanus.iron_blacksmith_gavel')]),
  e.addItem('forbidden_arcanus:diamond_blacksmith_gavel', [Component.translate('info.forbidden_arcanus.diamond_blacksmith_gavel')]),
  e.addItem('forbidden_arcanus:netherite_blacksmith_gavel', [Component.translate('info.forbidden_arcanus.netherite_blacksmith_gavel')]),
  e.addItem('forbidden_arcanus:reinforced_deorum_blacksmith_gavel', [Component.translate('info.forbidden_arcanus.reinforced_deorum_blacksmith_gavel')]),
  e.addItem('forbidden_arcanus:darkstone_upgrade_smithing_template', [Component.translate('info.forbidden_arcanus.darkstone_upgrade_smithing_template')]),
  e.addItem('forbidden_arcanus:eternal_stella', [Component.translate('info.forbidden_arcanus.eternal_stella')]),
  e.addItem('forbidden_arcanus:smelter_prism', [Component.translate('info.forbidden_arcanus.smelter_prism')]),
  e.addItem('forbidden_arcanus:terrastomp_prism', [Component.translate('info.forbidden_arcanus.terrastomp_prism')]),
  e.addItem('forbidden_arcanus:sea_prism', [Component.translate('info.forbidden_arcanus.sea_prism')]),
  e.addItem('forbidden_arcanus:whirlwind_prism', [Component.translate('info.forbidden_arcanus.whirlwind_prism')]),
  e.addItem('forbidden_arcanus:hephaestus_forge', [Component.translate('info.forbidden_arcanus.hephaestus_forge')]),
  e.addItem('forbidden_arcanus:draco_arcanus_arrow', [Component.translate('info.forbidden_arcanus.draco_arcanus_arrow')]),
  e.addItem('forbidden_arcanus:artisan_relic', [Component.translate('info.forbidden_arcanus.artisan_relic')]),
  e.addItem('forbidden_arcanus:crimson_stone', [Component.translate('info.forbidden_arcanus.crimson_stone')]),
  e.addItem('forbidden_arcanus:elementarium', [Component.translate('info.forbidden_arcanus.elementarium')]),
  e.addItem('forbidden_arcanus:crescent_moon', [Component.translate('info.forbidden_arcanus.crescent_moon')]),
  e.addItem('iceandfire:ice_dragon_blood', [Component.translate('info.iceandfire.ice_dragon_blood')]),
  e.addItem('iceandfire:fire_dragon_blood', [Component.translate('info.iceandfire.fire_dragon_blood')]),
  e.addItem('iceandfire:lightning_dragon_blood', [Component.translate('info.iceandfire.lightning_dragon_blood')]),
  e.addItem('alexsmobs:blood_sac', [Component.translate('info.alexsmobs.blood_sac')]),
  e.addItem('hexerei:blood_bottle', [Component.translate('info.hexerei.blood_bottle')]),
  e.addItem('hexerei:blood_bucket', [Component.translate('info.hexerei.blood_bucket')]),
  e.addItem('forbidden_arcanus:blood_test_tube', [Component.translate('info.forbidden_arcanus.blood_test_tube')]),
  e.addItem('forbidden_arcanus:soul', [Component.translate('info.forbidden_arcanus.soul')]),
  e.addItem('forbidden_arcanus:enchanted_soul', [Component.translate('info.forbidden_arcanus.enchanted_soul')]),
  e.addItem('forbidden_arcanus:corrupt_soul', [Component.translate('info.forbidden_arcanus.corrupt_soul')]),
  e.addItem('iceandfire:ectoplasm', [Component.translate('info.iceandfire.ectoplasm')]),
  e.addItem('alexscaves:pure_darkness', [Component.translate('info.alexscaves.pure_darkness')]),
  e.addItem('alexsmobs:skreecher_soul', [Component.translate('info.alexsmobs.skreecher_soul')]),
  e.addItem('alexsmobs:soul_heart', [Component.translate('info.alexsmobs.soul_heart')]),
  e.addItem('quark:soul_bead', [Component.translate('info.quark.soul_bead')]),
  e.addItem('netherexp:will_o_wisp', [Component.translate('info.netherexp.will_o_wisp')]),
  e.addItem('netherexp:banshee_powder', [Component.translate('info.netherexp.banshee_powder')]),
  e.addItem('netherexp:banshee_rod', [Component.translate('info.netherexp.banshee_rod')]),
  e.addItem('forbidden_arcanus:xpetrified_orb', [Component.translate('info.forbidden_arcanus.xpetrified_orb')]),
  e.addItem('create:experience_block', [Component.translate('info.create.experience_block')]),
  e.addItem('create:experience_nugget', [Component.translate('info.create.experience_nugget')]),
  e.addItem('ars_nouveau:experience_gem', [Component.translate('info.ars_nouveau.experience_gem')]),
  e.addItem('ars_nouveau:greater_experience_gem', [Component.translate('info.ars_nouveau.greater_experience_gem')]),
  e.addItem('ars_technica:giant_experience_gem', [Component.translate('info.ars_technica.giant_experience_gem')]),
  e.addItem('ars_technica:gargantuan_experience_gem', [Component.translate('info.ars_technica.gargantuan_experience_gem')]),
  e.addItem('minecraft:experience_bottle', [Component.translate('info.minecraft.experience_bottle')]),
  e.addItem('create_enchantment_industry:hyper_experience_bottle', [Component.translate('info.create_enchantment_industry.hyper_experience_bottle')]),
  e.addItem('forbidden_arcanus:arcane_crystal_dust', [Component.translate('info.forbidden_arcanus.arcane_crystal_dust')]),
  e.addItem('iceandfire:pixie_dust', [Component.translate('info.iceandfire.pixie_dust')]),
  e.addItem('waystones:warp_dust', [Component.translate('info.waystones.warp_dust')]),
  e.addItem('born_in_chaos_v1:spiritual_dust', [Component.translate('info.born_in_chaos_v1.spiritual_dust')]),
  e.addItem('illagerinvasion:illusionary_dust', [Component.translate('info.illagerinvasion.illusionary_dust')]),
  e.addItem('illagerinvasion:unusual_dust', ['Adds Aureal to the Hephaestus Forge. You can automatically generate it with Arcane Crystal Obelisks.'])
  e.addItem('betterend:crystal_shards', ['Adds Aureal to the Hephaestus Forge. You can automatically generate it with Arcane Crystal Obelisks.'])
  e.addItem('betterend:eternal_crystal', ['Adds Aureal to the Hephaestus Forge. You can automatically generate it with Arcane Crystal Obelisks.'])

//Friends and Foes
  e.addItem('friendsandfoes:wildfire_crown', [Component.translate('info.friendsandfoes.wildfire_crown')]),
  e.addItem('friendsandfoes:totem_of_freezing', [Component.translate('info.friendsandfoes.totem_of_freezing')]),
  e.addItem('friendsandfoes:totem_of_illusion', [Component.translate('info.friendsandfoes.totem_of_illusion')]),
  e.addItem('friendsandfoes:copper_golem_spawn_egg', [Component.translate('info.friendsandfoes.copper_golem_spawn_egg')]),
  e.addItem('friendsandfoes:tuff_golem_spawn_egg', [Component.translate('info.friendsandfoes.tuff_golem_spawn_egg')]),
  e.addItem('friendsandfoes:glare_spawn_egg', [Component.translate('info.friendsandfoes.glare_spawn_egg')]),
  e.addItem('friendsandfoes:mauler_spawn_egg', [Component.translate('info.friendsandfoes.mauler_spawn_egg')]),

//Galosphere
    e.addItem('galosphere:sterling_horse_armor', [Component.translate('info.galosphere.sterling_horse_armor')]),
    e.addItem('galosphere:silver_bomb', [Component.translate('info.galosphere.silver_bomb')]),
    e.addItem('galosphere:combustion_table', [Component.translate('info.galosphere.combustion_table')]),
    e.addItem('galosphere:silver_balance', [Component.translate('info.galosphere.silver_balance')]),
    e.addItem('galosphere:silver_lattice', [Component.translate('info.galosphere.silver_lattice')]),
    e.addItem('galosphere:glow_flare', [Component.translate('info.galosphere.glow_flare')]),
    e.addItem('galosphere:glow_ink_clumps', [Component.translate('info.galosphere.glow_ink_clumps')]),
    e.addItem('galosphere:lichen_moss', [Component.translate('info.galosphere.lichen_moss')]),
    e.addItem('galosphere:spectre_flare', [Component.translate('info.galosphere.spectre_flare')]),
    e.addItem('galosphere:bottle_of_spectre', [Component.translate('info.galosphere.bottle_of_spectre')]),
    e.addItem('galosphere:spectre_spawn_egg', [Component.translate('info.galosphere.spectre_spawn_egg')]),
    e.addItem('galosphere:specterpillar_spawn_egg', [Component.translate('info.galosphere.specterpillar_spawn_egg')]),
    e.addItem('galosphere:allurite_shard', [Component.translate('info.galosphere.allurite_shard')]),
    e.addItem('galosphere:lichen_shelf', [Component.translate('info.galosphere.lichen_shelf')]),
    e.addItem('galosphere:lichen_cordyceps', [Component.translate('info.galosphere.lichen_cordyceps')]),
    e.addItem('galosphere:golden_lichen_cordyceps', [Component.translate('info.galosphere.golden_lichen_cordyceps')]),
    e.addItem('galosphere:allurite_block', [Component.translate('info.galosphere.allurite_block')]),
    e.addItem('galosphere:warped_anchor', [Component.translate('info.galosphere.warped_anchor')]),
    e.addItem('galosphere:lumiere_block', [Component.translate('info.galosphere.lumiere_block')]),
    e.addItem('galosphere:charged_lumiere_block', [Component.translate('info.galosphere.charged_lumiere_block')]),
    e.addItem('galosphere:lumiere_shard', [Component.translate('info.galosphere.lumiere_shard')]),
    e.addItem('minecraft:glowstone_dust', [Component.translate('info.minecraft.glowstone_dust')]),
    e.addItem('galosphere:monstrometer', [Component.translate('info.galosphere.monstrometer')]),
    e.addItem('galosphere:sparkle_spawn_egg', [Component.translate('info.galosphere.sparkle_spawn_egg')]),
    e.addItem('minecraft:amethyst_cluster', [Component.translate('info.minecraft.amethyst_cluster')]),
    e.addItem('galosphere:glinted_amethyst_cluster', [Component.translate('info.galosphere.glinted_amethyst_cluster')]),
    e.addItem('galosphere:allurite_cluster', [Component.translate('info.galosphere.allurite_cluster')]),
    e.addItem('galosphere:glinted_allurite_cluster', [Component.translate('info.galosphere.glinted_allurite_cluster')]),
    e.addItem('galosphere:lumiere_cluster', [Component.translate('info.galosphere.lumiere_cluster')]),
    e.addItem('galosphere:glinted_lumiere_cluster', [Component.translate('info.galosphere.glinted_lumiere_cluster')]),
    e.addItem('galosphere:pink_salt', [Component.translate('info.galosphere.pink_salt')]),
    e.addItem('galosphere:rose_pink_salt', [Component.translate('info.galosphere.rose_pink_salt')]),
    e.addItem('galosphere:pastel_pink_salt', [Component.translate('info.galosphere.pastel_pink_salt')]),
    e.addItem('galosphere:pink_salt_straw', [Component.translate('info.galosphere.pink_salt_straw')]),
    e.addItem('minecraft:coarse_dirt', [Component.translate('info.minecraft.coarse_dirt')]),
    e.addItem('galosphere:shadow_frame', [Component.translate('info.galosphere.shadow_frame')]),
    e.addItem('galosphere:stranded_membrane_block', [Component.translate('info.galosphere.stranded_membrane_block')]),
    e.addItem('galosphere:preserved_flesh', [Component.translate('info.galosphere.preserved_flesh')]),
    e.addItem('galosphere:saltbound_tablet', [Component.translate('info.galosphere.saltbound_tablet')]),
    e.addItem('galosphere:pink_salt_chamber', [Component.translate('info.galosphere.pink_salt_chamber')]),
    e.addItem('galosphere:pink_salt_cluster', [Component.translate('info.galosphere.pink_salt_cluster')]),
    e.addItem('galosphere:barometer', [Component.translate('info.galosphere.barometer')]),


//Hellion's Sniffer Plus
  e.addItem('minecraft:torchflower', [Component.translate('info.minecraft.torchflower')]),
  e.addItem('minecraft:sniffer_egg', [Component.translate('info.minecraft.sniffer_egg')]),

//Incubation
  e.addItem('incubation:twig_nest', [Component.translate('info.incubation.twig_nest')]),
  e.addItem('incubation:hay_nest', [Component.translate('info.incubation.hay_nest')]),

//Jaden's Nether Expansion
  e.addItem('netherexp:souled_geyser', [Component.translate('info.netherexp.souled_geyser')]),
  e.addItem('netherexp:basaltic_geyser', [Component.translate('info.netherexp.basaltic_geyser')]),
  e.addItem('netherexp:crimson_sporeshroom', [Component.translate('info.netherexp.crimson_sporeshroom')]),
  e.addItem('netherexp:warped_sporeshroom', [Component.translate('info.netherexp.warped_sporeshroom')]),
  e.addItem('netherexp:lightspores', [Component.translate('info.netherexp.lightspores')]),
  e.addItem('netherexp:nightspores', [Component.translate('info.netherexp.nightspores')]),
  e.addItem('minecraft:crimson_nylium', [Component.translate('info.minecraft.crimson_nylium')]),
  e.addItem('minecraft:warped_nylium', [Component.translate('info.minecraft.warped_nylium')]),
  e.addItem('minecraft:soul_sand', [Component.translate('info.minecraft.soul_sand')]),
  e.addItem('netherexp:soul_path', [Component.translate('info.netherexp.soul_path')]),
  e.addItem('netherexp:warped_nylium_path', [Component.translate('info.netherexp.warped_nylium_path')]),
  e.addItem('netherexp:crimson_nylium_path', [Component.translate('info.netherexp.crimson_nylium_path')]),
  e.addItem('netherexp:soul_swirls', [Component.translate('info.netherexp.soul_swirls')]),
  e.addItem('netherexp:chiseled_soul_slate_bricks', [Component.translate('info.netherexp.chiseled_soul_slate_bricks')]),
  e.addItem('netherexp:etched_soul_slate_bricks', [Component.translate('info.netherexp.etched_soul_slate_bricks')]),
  e.addItem('netherexp:chiseled_soul_slate_tiles', [Component.translate('info.netherexp.chiseled_soul_slate_tiles')]),
  e.addItem('netherexp:etched_soul_slate_tiles', [Component.translate('info.netherexp.etched_soul_slate_tiles')]),
  e.addItem('netherexp:soul_magma_block', [Component.translate('info.netherexp.soul_magma_block')]),
  e.addItem('netherexp:fossil_ore', [Component.translate('info.netherexp.fossil_ore')]),
  e.addItem('netherexp:fossil_fuel_ore', [Component.translate('info.netherexp.fossil_fuel_ore')]),
  e.addItem('netherexp:fossil_fuel', [Component.translate('info.netherexp.fossil_fuel')]),
  e.addItem('netherexp:ectoplasm_bucket', [Component.translate('info.netherexp.ectoplasm_bucket')]),
  e.addItem('netherexp:black_ice', [Component.translate('info.netherexp.black_ice')]),
  e.addItem('netherexp:bone_cortical', [Component.translate('info.netherexp.bone_cortical')]),
  e.addItem('netherexp:stridite', [Component.translate('info.netherexp.stridite')]),
  e.addItem('netherexp:treacherous_flame', [Component.translate('info.netherexp.treacherous_flame')]),
  e.addItem('netherexp:treacherous_candle', [Component.translate('info.netherexp.treacherous_candle')]),
  e.addItem('netherexp:brazier_chest', [Component.translate('info.netherexp.brazier_chest')]),
  e.addItem('netherexp:sculk_grinder', [Component.translate('info.netherexp.sculk_grinder')]),
  e.addItem('netherexp:shotgun_fist', [Component.translate('info.netherexp.shotgun_fist')]),
  e.addItem('netherexp:wraithing_flesh', [Component.translate('info.netherexp.wraithing_flesh')]),
  e.addItem('netherexp:pump_charge_shotgun', [Component.translate('info.netherexp.pump_charge_shotgun')]),
  e.addItem('netherexp:will_o_wisp', [Component.translate('info.netherexp.will_o_wisp')]),
  e.addItem('netherexp:phasmo_arrow', [Component.translate('info.netherexp.phasmo_arrow')]),
  e.addItem('netherexp:soul_glass', [Component.translate('info.netherexp.soul_glass')]),
  e.addItem('netherexp:ochre_frogmist', [Component.translate('info.netherexp.ochre_frogmist')]),
  e.addItem('netherexp:verdant_frogmist', [Component.translate('info.netherexp.verdant_frogmist')]),
  e.addItem('netherexp:pearlescent_frogmist', [Component.translate('info.netherexp.pearlescent_frogmist')]),
  e.addItem('netherexp:sorrowsquash', [Component.translate('info.netherexp.sorrowsquash')]),
  e.addItem('netherexp:netherite_plated_block', [Component.translate('info.netherexp.netherite_plated_block')]),
  e.addItem('netherexp:netherite_grate', [Component.translate('info.netherexp.netherite_grate')]),
  e.addItem('netherexp:cut_netherite_block', [Component.translate('info.netherexp.cut_netherite_block')]),
  e.addItem('netherexp:cut_netherite_stairs', [Component.translate('info.netherexp.cut_netherite_stairs')]),
  e.addItem('netherexp:cut_netherite_slab', [Component.translate('info.netherexp.cut_netherite_slab')]),
  e.addItem('netherexp:cut_netherite_pillar', [Component.translate('info.netherexp.cut_netherite_pillar')]),
  e.addItem('netherexp:rusty_netherite_plated_block', [Component.translate('info.netherexp.rusty_netherite_plated_block')]),
  e.addItem('netherexp:rusty_netherite_grate', [Component.translate('info.netherexp.rusty_netherite_grate')]),
  e.addItem('netherexp:rusty_cut_netherite_block', [Component.translate('info.netherexp.rusty_cut_netherite_block')]),
  e.addItem('netherexp:rusty_cut_netherite_stairs', [Component.translate('info.netherexp.rusty_cut_netherite_stairs')]),
  e.addItem('netherexp:rusty_cut_netherite_slab', [Component.translate('info.netherexp.rusty_cut_netherite_slab')]),
  e.addItem('netherexp:rusty_cut_netherite_pillar', [Component.translate('info.netherexp.rusty_cut_netherite_pillar')]),
  e.addItem('netherexp:inscribed_panel', [Component.translate('info.netherexp.inscribed_panel')]),
  e.addItem('netherexp:ossified_gargoyle_statue', [Component.translate('info.netherexp.ossified_gargoyle_statue')]),
  e.addItem('netherexp:trample_gargoyle_statue', [Component.translate('info.netherexp.trample_gargoyle_statue')]),
  e.addItem('netherexp:phase_gargoyle_statue', [Component.translate('info.netherexp.phase_gargoyle_statue')]),
  e.addItem('netherexp:ghoul_gargoyle_statue', [Component.translate('info.netherexp.ghoul_gargoyle_statue')]),
  e.addItem('netherexp:wretched_gargoyle_statue', [Component.translate('info.netherexp.wretched_gargoyle_statue')]),
  e.addItem('netherexp:treacherous_gargoyle_statue', [Component.translate('info.netherexp.treacherous_gargoyle_statue')]),
  e.addItem('netherexp:cirripedia_gargoyle_statue', [Component.translate('info.netherexp.cirripedia_gargoyle_statue')]),
  e.addItem('netherexp:occult_gargoyle_statue', [Component.translate('info.netherexp.occult_gargoyle_statue')]),
  e.addItem('netherexp:sealed_gargoyle_statue', [Component.translate('info.netherexp.sealed_gargoyle_statue')]),
  e.addItem('netherexp:obfuscated_gargoyle_statue', [Component.translate('info.netherexp.obfuscated_gargoyle_statue')]),
  e.addItem('netherexp:antidote', [Component.translate('info.netherexp.antidote')]),
  e.addItem('netherexp:grenade_antidote', [Component.translate('info.netherexp.grenade_antidote')]),

 //Oreganized
  e.addItem('oreganized:silver_mirror', [Component.translate('info.oreganized.silver_mirror')]),
  e.addItem('oreganized:lead_bars', [Component.translate('info.oreganized.lead_bars')]),
  e.addItem('oreganized:lead_door', [Component.translate('info.oreganized.lead_door')]),
  e.addItem('oreganized:lead_trapdoor', [Component.translate('info.oreganized.lead_trapdoor')]),
  e.addItem('oreganized:lead_block', [Component.translate('info.oreganized.lead_block')]),
  e.addItem('oreganized:cut_lead', [Component.translate('info.oreganized.cut_lead')]),
  e.addItem('oreganized:lead_bricks', [Component.translate('info.oreganized.lead_bricks')]),
  e.addItem('oreganized:lead_pillar', [Component.translate('info.oreganized.lead_pillar')]),
  e.addItem('oreganized:lead_bulb', [Component.translate('info.oreganized.lead_bulb')]),
  e.addItem('oreganized:lead_bolt', [Component.translate('info.oreganized.lead_bolt')]),
  e.addItem('oreganized:gargoyle', [Component.translate('info.oreganized.gargoyle')]),
  e.addItem('oreganized:electrum_upgrade_smithing_template', [Component.translate('info.oreganized.electrum_upgrade_smithing_template')]),
  e.addItem('oreganized:scribe', [Component.translate('info.oreganized.scribe')]),

//Doom and Gloom
  e.addItem('doom_and_gloom:sepulcher', [Component.translate('info.doom_and_gloom.sepulcher')]),
  e.addItem('doom_and_gloom:burial_dirt', [Component.translate('info.doom_and_gloom.burial_dirt')]),

//Rubinated Nether
  e.addItem('rubinated_nether:ruby', [Component.translate('info.rubinated_nether.ruby')]),
  e.addItem('rubinated_nether:molten_ruby', [Component.translate('info.rubinated_nether.molten_ruby')]),
  e.addItem('rubinated_nether:nether_ruby_ore', [Component.translate('info.rubinated_nether.nether_ruby_ore')]),
  e.addItem('rubinated_nether:molten_ruby_ore', [Component.translate('info.rubinated_nether.molten_ruby_ore')]),
  e.addItem('rubinated_nether:soakstone', [Component.translate('info.rubinated_nether.soakstone')]),
  e.addItem('rubinated_nether:ruby_shard', [Component.translate('info.rubinated_nether.ruby_shard')]),

//Supplementaries
  e.addItem('supplementaries:slingshot', [Component.translate('info.supplementaries.slingshot')]),
  e.addItem('supplementaries:quiver', [Component.translate('info.supplementaries.quiver')]),
  e.addItem('supplementaries:slice_map', [Component.translate('info.supplementaries.slice_map')]),
  e.addItem('supplementaries:flute', [Component.translate('info.supplementaries.flute')]),
  e.addItem('supplementaries:wrench', [Component.translate('info.supplementaries.wrench')]),
  e.addItem('supplementaries:soap', [Component.translate('info.supplementaries.soap')]),
  e.addItem('supplementaries:bubble_blower', [Component.translate('info.supplementaries.bubble_blower')]),
  e.addItem('supplementaries:antique_ink', [Component.translate('info.supplementaries.antique_ink')]),
  e.addItem('supplementaries:key', [Component.translate('info.supplementaries.key')]),
  e.addItem('supplementaries:pancake', [Component.translate('info.supplementaries.pancake')]),

//Storage Drawers
e.addItem('storagedrawers:controller', [Component.translate('info.storagedrawers.controller')]),

//Upgrade Aquatic
  e.addItem('upgrade_aquatic:tooth_door', [Component.translate('info.upgrade_aquatic.tooth_door')]),
  e.addItem('upgrade_aquatic:tooth_trapdoor', [Component.translate('info.upgrade_aquatic.tooth_trapdoor')]),
  e.addItem('upgrade_aquatic:coralstone', [Component.translate('info.upgrade_aquatic.coralstone')]),
  e.addItem('upgrade_aquatic:tube_coralstone', [Component.translate('info.upgrade_aquatic.tube_coralstone')]),
  e.addItem('upgrade_aquatic:brain_coralstone', [Component.translate('info.upgrade_aquatic.brain_coralstone')]),
  e.addItem('upgrade_aquatic:bubble_coralstone', [Component.translate('info.upgrade_aquatic.bubble_coralstone')]),
  e.addItem('upgrade_aquatic:fire_coralstone', [Component.translate('info.upgrade_aquatic.fire_coralstone')]),
  e.addItem('upgrade_aquatic:horn_coralstone', [Component.translate('info.upgrade_aquatic.horn_coralstone')]),
  e.addItem('upgrade_aquatic:acan_coralstone', [Component.translate('info.upgrade_aquatic.acan_coralstone')]),
  e.addItem('upgrade_aquatic:finger_coralstone', [Component.translate('info.upgrade_aquatic.finger_coralstone')]),
  e.addItem('upgrade_aquatic:star_coralstone', [Component.translate('info.upgrade_aquatic.star_coralstone')]),
  e.addItem('upgrade_aquatic:moss_coralstone', [Component.translate('info.upgrade_aquatic.moss_coralstone')]),
  e.addItem('upgrade_aquatic:petal_coralstone', [Component.translate('info.upgrade_aquatic.petal_coralstone')]),
  e.addItem('upgrade_aquatic:branch_coralstone', [Component.translate('info.upgrade_aquatic.branch_coralstone')]),
  e.addItem('upgrade_aquatic:rock_coralstone', [Component.translate('info.upgrade_aquatic.rock_coralstone')]),
  e.addItem('upgrade_aquatic:pillow_coralstone', [Component.translate('info.upgrade_aquatic.pillow_coralstone')]),
  e.addItem('upgrade_aquatic:silk_coralstone', [Component.translate('info.upgrade_aquatic.silk_coralstone')]),
  e.addItem('upgrade_aquatic:chrome_coralstone', [Component.translate('info.upgrade_aquatic.chrome_coralstone')]),
  e.addItem('upgrade_aquatic:prismarine_coralstone', [Component.translate('info.upgrade_aquatic.prismarine_coralstone')]),
  e.addItem('upgrade_aquatic:bedroll', [Component.translate('info.upgrade_aquatic.bedroll')]),
  e.addItem('upgrade_aquatic:white_bedroll', [Component.translate('info.upgrade_aquatic.white_bedroll')]),
  e.addItem('upgrade_aquatic:light_gray_bedroll', [Component.translate('info.upgrade_aquatic.light_gray_bedroll')]),
  e.addItem('upgrade_aquatic:gray_bedroll', [Component.translate('info.upgrade_aquatic.gray_bedroll')]),
  e.addItem('upgrade_aquatic:black_bedroll', [Component.translate('info.upgrade_aquatic.black_bedroll')]),
  e.addItem('upgrade_aquatic:brown_bedroll', [Component.translate('info.upgrade_aquatic.brown_bedroll')]),
  e.addItem('upgrade_aquatic:red_bedroll', [Component.translate('info.upgrade_aquatic.red_bedroll')]),
  e.addItem('upgrade_aquatic:orange_bedroll', [Component.translate('info.upgrade_aquatic.orange_bedroll')]),
  e.addItem('upgrade_aquatic:yellow_bedroll', [Component.translate('info.upgrade_aquatic.yellow_bedroll')]),
  e.addItem('upgrade_aquatic:lime_bedroll', [Component.translate('info.upgrade_aquatic.lime_bedroll')]),
  e.addItem('upgrade_aquatic:green_bedroll', [Component.translate('info.upgrade_aquatic.green_bedroll')]),
  e.addItem('upgrade_aquatic:cyan_bedroll', [Component.translate('info.upgrade_aquatic.cyan_bedroll')]),
  e.addItem('upgrade_aquatic:light_blue_bedroll', [Component.translate('info.upgrade_aquatic.light_blue_bedroll')]),
  e.addItem('upgrade_aquatic:blue_bedroll', [Component.translate('info.upgrade_aquatic.blue_bedroll')]),
  e.addItem('upgrade_aquatic:purple_bedroll', [Component.translate('info.upgrade_aquatic.purple_bedroll')]),
  e.addItem('upgrade_aquatic:magenta_bedroll', [Component.translate('info.upgrade_aquatic.magenta_bedroll')]),
  e.addItem('upgrade_aquatic:pink_bedroll', [Component.translate('info.upgrade_aquatic.pink_bedroll')]),
  e.addItem('upgrade_aquatic:pickerelweed_block', [Component.translate('info.upgrade_aquatic.pickerelweed_block')]),
  e.addItem('upgrade_aquatic:boiled_pickerelweed_block', [Component.translate('info.upgrade_aquatic.boiled_pickerelweed_block')]),
  e.addItem('upgrade_aquatic:elder_eye', [Component.translate('info.upgrade_aquatic.elder_eye')]),
  e.addItem('upgrade_aquatic:pike_spawn_egg', [Component.translate('info.upgrade_aquatic.pike_spawn_egg')]),
  e.addItem('upgrade_aquatic:mulberry', [Component.translate('info.upgrade_aquatic.mulberry')]),
  e.addItem('minecraft:glow_ink_sac', [Component.translate('info.minecraft.glow_ink_sac')]),

//Simply Swords
  e.addItem('simplyswords:runefused_gem', [Component.translate('info.simplyswords.runefused_gem')]),
  e.addItem('simplyswords:netherfused_gem', [Component.translate('info.simplyswords.netherfused_gem')]),
  e.addItem('simplyswords:empowered_remnant', [Component.translate('info.simplyswords.empowered_remnant')]),
  e.addItem('simplyswords:brimstone_claymore', [Component.translate('info.simplyswords.brimstone_claymore')]),
  e.addItem('simplyswords:watcher_claymore', [Component.translate('info.simplyswords.watcher_claymore')]),
  e.addItem('simplyswords:storms_edge', [Component.translate('info.simplyswords.storms_edge')]),
  e.addItem('simplyswords:stormbringer', [Component.translate('info.simplyswords.stormbringer')]),
  e.addItem('simplyswords:bramblethorn', [Component.translate('info.simplyswords.bramblethorn')]),
  e.addItem('simplyswords:watching_warglaive', [Component.translate('info.simplyswords.watching_warglaive')]),
  e.addItem('simplyswords:toxic_longsword', [Component.translate('info.simplyswords.toxic_longsword')]),
  e.addItem('simplyswords:emberblade', [Component.translate('info.simplyswords.emberblade')]),
  e.addItem('simplyswords:hearthflame', [Component.translate('info.simplyswords.hearthflame')]),
  e.addItem('simplyswords:soulkeeper', [Component.translate('info.simplyswords.soulkeeper')]),
  e.addItem('simplyswords:twisted_blade', [Component.translate('info.simplyswords.twisted_blade')]),
  e.addItem('simplyswords:soulstealer', [Component.translate('info.simplyswords.soulstealer')]),
  e.addItem('simplyswords:soulrender', [Component.translate('info.simplyswords.soulrender')]),
  e.addItem('simplyswords:soulpyre', [Component.translate('info.simplyswords.soulpyre')]),
  e.addItem('simplyswords:frostfall', [Component.translate('info.simplyswords.frostfall')]),
  e.addItem('simplyswords:molten_edge', [Component.translate('info.simplyswords.molten_edge')]),
  e.addItem('simplyswords:livyatan', [Component.translate('info.simplyswords.livyatan')]),
  e.addItem('simplyswords:icewhisper', [Component.translate('info.simplyswords.icewhisper')]),
  e.addItem('simplyswords:arcanethyst', [Component.translate('info.simplyswords.arcanethyst')]),
  e.addItem('simplyswords:thunderbrand', [Component.translate('info.simplyswords.thunderbrand')]),
  e.addItem('simplyswords:mjolnir', [Component.translate('info.simplyswords.mjolnir')]),
  e.addItem('simplyswords:slumbering_lichblade', [Component.translate('info.simplyswords.slumbering_lichblade')]),
  e.addItem('simplyswords:shadowsting', [Component.translate('info.simplyswords.shadowsting')]),
  e.addItem('simplyswords:whisperwind', [Component.translate('info.simplyswords.whisperwind')]),
  e.addItem('simplyswords:emberlash', [Component.translate('info.simplyswords.emberlash')]),
  e.addItem('simplyswords:waxweaver', [Component.translate('info.simplyswords.waxweaver')]),
  e.addItem('simplyswords:hiveheart', [Component.translate('info.simplyswords.hiveheart')]),
  e.addItem('simplyswords:stars_edge', [Component.translate('info.simplyswords.stars_edge')]),
  e.addItem('simplyswords:wickpiercer', [Component.translate('info.simplyswords.wickpiercer')]),
  e.addItem('simplyswords:tempest', [Component.translate('info.simplyswords.tempest')]),
  e.addItem('simplyswords:flamewind', [Component.translate('info.simplyswords.flamewind')]),
  e.addItem('simplyswords:ribboncleaver', [Component.translate('info.simplyswords.ribboncleaver')]),
  e.addItem('simplyswords:enigma', [Component.translate('info.simplyswords.enigma')]),
  e.addItem('simplyswords:magiscythe', [Component.translate('info.simplyswords.magiscythe')]),
  e.addItem('simplyswords:magispear', [Component.translate('info.simplyswords.magispear')]),
  e.addItem('simplyswords:magiblade', [Component.translate('info.simplyswords.magiblade')]),
  e.addItem('simplyswords:caelestis', [Component.translate('info.simplyswords.caelestis')]),
  e.addItem('simplyswords:decaying_relic', [Component.translate('info.simplyswords.decaying_relic')]),

//Wilder Wild
  e.addItem('wilderwild:stone_chest', [Component.translate('info.wilderwild.stone_chest')]),
  e.addItem('wilderwild:termite_mound', [Component.translate('info.wilderwild.termite_mound')]),
  e.addItem('wilderwild:ancient_horn', [Component.translate('info.wilderwild.ancient_horn')]),
  e.addItem('wilderwild:prickly_pear', [Component.translate('info.wilderwild.prickly_pear')]),
  e.addItem('wilderwild:echo_glass', [Component.translate('info.wilderwild.echo_glass')]),

  e.addItem('delightful:animal_fat', [Component.translate('info.delightful.animal_fat')]),

//Hexerei
  e.addItem('hexerei:witch_helmet', [Component.translate('info.hexerei.witch_helmet')]),
  e.addItem('hexerei:mushroom_witch_hat', [Component.translate('info.hexerei.mushroom_witch_hat')]),

//Re:Deco
  e.addItem('redeco:hammer', [Component.translate('info.redeco.hammer')]),

//Ice and Fire
  e.addItem('iceandfire:ambrosia', [Component.translate('info.iceandfire.ambrosia')]),

//Locator Eyes
//  e.addItem('eyesoficeandfire:eye_of_fire_dragon', ['Points to nearby Fire Dragons.']),
//  e.addItem('eyesoficeandfire:eye_of_ice_dragon', ['Points to nearby Ice Dragons.']),
//  e.addItem('eyesoficeandfire:eye_of_lightning_dragon', ['Points to nearby Lightning Dragons.']),
//  e.addItem('cataclysm:flame_eye', ['Points to the Burning Arena in the Nether.']),
//  e.addItem('cataclysm:mech_eye', ['Points to the Ancient Factory.']),
//  e.addItem('cataclysm:void_eye', ['Points to the Ruined Citadel in the End.']),
//  e.addItem('cataclysm:monstrous_eye', ['Points to the Soul Blacksmith.']),
//  e.addItem('cataclysm:abyss_eye', ['Points to the Sunken City.']),
//  e.addItem('cataclysm:desert_eye', ['Points to the Cursed Pyramid.']),
//  e.addItem('cataclysm:cursed_eye', ['Points to the Frosted Prison.']),
//  e.addItem('mowzies_cataclysm:sun_eye', ['Points to the Umuvthana Grove.']),
//  e.addItem('mowzies_cataclysm:frostmaw_eye', ['Points to the Frostmaw.']),
//  e.addItem('mowzies_cataclysm:wrought_eye', ['Points to the Wrought Chamber.']),

//Cataclysm
//  e.addItem('cataclysm:abyssal_sacrifice', ['Use in the Sunken City to summon The Leviathan.']),
//  e.addItem('cataclysm:burning_ashes', ['Used in the Burning Arena to summon the Ignis.']),

//Born in Chaos
  e.addItem('born_in_chaos_v1:fel_lamp', [Component.translate('info.born_in_chaos_v1.fel_lamp')]),
  e.addItem('born_in_chaos_v1:fused_bone', [Component.translate('info.born_in_chaos_v1.fused_bone')]),
  e.addItem('born_in_chaos_v1:phantom_bomb', [Component.translate('info.born_in_chaos_v1.phantom_bomb')]),
  e.addItem('born_in_chaos_v1:evil_carved_pumpkin', [Component.translate('info.born_in_chaos_v1.evil_carved_pumpkin')]),
  e.addItem('born_in_chaos_v1:dark_upgrade', [Component.translate('info.born_in_chaos_v1.dark_upgrade')]),
  e.addItem('born_in_chaos_v1:transmuting_elixir', [Component.translate('info.born_in_chaos_v1.transmuting_elixir')]),
  e.addItem('born_in_chaos_v1:infernal_evil_pumpkin', [Component.translate('info.born_in_chaos_v1.infernal_evil_pumpkin')]),
  e.addItem('born_in_chaos_v1:pumpkinhandgun', [Component.translate('info.born_in_chaos_v1.pumpkinhandgun')]),
  e.addItem('born_in_chaos_v1:soulbane', [Component.translate('info.born_in_chaos_v1.soulbane')]),
  e.addItem('born_in_chaos_v1:smoldering_infernal_ember', [Component.translate('info.born_in_chaos_v1.smoldering_infernal_ember')]),
  e.addItem('born_in_chaos_v1:potion_of_rampage', [Component.translate('info.born_in_chaos_v1.potion_of_rampage')]),
  e.addItem('born_in_chaos_v1:elixirof_wither_resistance', [Component.translate('info.born_in_chaos_v1.elixirof_wither_resistance')]),
  e.addItem('born_in_chaos_v1:elixir_of_vampirism', [Component.translate('info.born_in_chaos_v1.elixir_of_vampirism')]),
  e.addItem('born_in_chaos_v1:darkwarblade', [Component.translate('info.born_in_chaos_v1.darkwarblade')]),
  e.addItem('born_in_chaos_v1:spider_bite_sword', [Component.translate('info.born_in_chaos_v1.spider_bite_sword')]),

  e.addItem('ars_additions:enchanting_wixie_cauldron', ['Use a Wixie charm on an enchanting aparatus to create. Can be used to automate enchanting.'])
  e.addItem('ars_nouveau:scribes_table', ['Used for creating Glyphs.'])

//Eidolong
  e.addItem('eidolon:reaper_scythe', [Component.translate('info.eidolon.reaper_scythe')]),
  e.addItem('eidolon:soul_shard', [Component.translate('info.eidolon.soul_shard')]),
  e.addItem('eidolon:top_hat', [Component.translate('info.eidolon.top_hat')]),
  e.addItem('eidolon:stone_altar', [Component.translate('info.eidolon.stone_altar')]),
  e.addItem('eidolon:candlestick', [Component.translate('info.eidolon.candlestick')]),
  e.addItem('eidolon:magic_candle', [Component.translate('info.eidolon.magic_candle')]),
  e.addItem('eidolon:magic_candlestick', [Component.translate('info.eidolon.magic_candlestick')]),
  e.addItem('eidolon:straw_effigy', [Component.translate('info.eidolon.straw_effigy')]),
  e.addItem('eidolon:censer', [Component.translate('info.eidolon.censer')]),
  e.addItem('eidolon:goblet', [Component.translate('info.eidolon.goblet')]),
  e.addItem('eidolon:unholy_effigy', [Component.translate('info.eidolon.unholy_effigy')]),
  e.addItem('eidolon:enervating_ring', [Component.translate('info.eidolon.enervating_ring')]),
  e.addItem('eidolon:cleaving_axe', [Component.translate('info.eidolon.cleaving_axe')]),
  e.addItem('eidolon:reversal_pick', [Component.translate('info.eidolon.reversal_pick')]),
  e.addItem('eidolon:sanguine_amulet', [Component.translate('info.eidolon.sanguine_amulet')]),
  e.addItem('eidolon:soulbone_amulet', [Component.translate('info.eidolon.soulbone_amulet')]),
  e.addItem('eidolon:bonelord_helm', [Component.translate('info.eidolon.bonelord_helm')]),
  e.addItem('eidolon:bonelord_chestplate', [Component.translate('info.eidolon.bonelord_chestplate')]),   e.addItem('eidolon:bonelord_greaves', [Component.translate('info.eidolon.bonelord_greaves')]),
  e.addItem('eidolon:soulfire_wand', [Component.translate('info.eidolon.soulfire_wand')]),
  e.addItem('eidolon:bonechill_wand', [Component.translate('info.eidolon.bonechill_wand')]),
  e.addItem('eidolon:mind_shielding_plate', [Component.translate('info.eidolon.mind_shielding_plate')]),
  e.addItem('eidolon:glass_hand', [Component.translate('info.eidolon.glass_hand')]),
  e.addItem('eidolon:angels_sight', [Component.translate('info.eidolon.angels_sight')]),
  e.addItem('eidolon:summoning_staff', [Component.translate('info.eidolon.summoning_staff')]),
  e.addItem('eidolon:deathbringer_scythe', [Component.translate('info.eidolon.deathbringer_scythe')]),
  e.addItem('eidolon:raven_cloak', [Component.translate('info.eidolon.raven_cloak')]),

//Critters and Companions
  e.addItem('crittersandcompanions:ferret_spawn_egg', [Component.translate('info.crittersandcompanions.ferret_spawn_egg')]),
  e.addItem('crittersandcompanions:leaf_insect_spawn_egg', [Component.translate('info.crittersandcompanions.leaf_insect_spawn_egg')]),
  e.addItem('crittersandcompanions:dragonfly_spawn_egg', [Component.translate('info.crittersandcompanions.dragonfly_spawn_egg')]),
  e.addItem('crittersandcompanions:red_panda_spawn_egg', [Component.translate('info.crittersandcompanions.red_panda_spawn_egg')]),
  e.addItem('crittersandcompanions:shima_enaga_spawn_egg', [Component.translate('info.crittersandcompanions.shima_enaga_spawn_egg')]),
  e.addItem('crittersandcompanions:jumping_spider_spawn_egg', [Component.translate('info.crittersandcompanions.jumping_spider_spawn_egg')])
})
